# Generated by Django 5.0.6 on 2026-02-26 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('tin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_tel_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
